# Generated by Django 3.2.10 on 2022-11-03 11:52

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('emp_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empofmonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('Empofmonth', models.CharField(blank=True, max_length=100, null=True)),
                ('Empofyear', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'empofmonth',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('month', models.CharField(blank=True, max_length=45, null=True)),
                ('payslip', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll',
            },
        ),
        migrations.CreateModel(
            name='LeaveManagement',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('approver', models.CharField(blank=True, max_length=45, null=True)),
                ('document', models.CharField(blank=True, max_length=45, null=True)),
                ('leave_type', models.CharField(blank=True, max_length=45, null=True)),
                ('leave_reason', models.TextField(blank=True, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_management',
            },
        ),
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.CharField(max_length=32)),
                ('month', models.CharField(max_length=45)),
                ('Details', models.FileField(blank=True, upload_to=account.models.upload_path)),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dependents',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, max_length=45, null=True)),
                ('dependent_name', models.TextField(blank=True, null=True)),
                ('relation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dependents',
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('asset', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, max_length=45, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('quarter', models.CharField(blank=True, max_length=45, null=True)),
                ('goal', models.CharField(blank=True, max_length=45, null=True)),
                ('goal_response', models.CharField(blank=True, max_length=45, null=True)),
                ('kpi', models.CharField(blank=True, max_length=45, null=True)),
                ('kpi_response', models.CharField(blank=True, max_length=45, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('jd', models.TextField(blank=True, null=True)),
                ('kd', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appraisal',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attacthment', models.ImageField(blank=True, upload_to=account.models.upload_path)),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('marital_status', models.CharField(blank=True, max_length=11, null=True)),
                ('email_id', models.CharField(blank=True, max_length=45, null=True)),
                ('phone_no', models.IntegerField()),
                ('emergency_no', models.IntegerField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=11, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=45, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('aadhar_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=16, null=True)),
                ('department_name', models.CharField(blank=True, max_length=45, null=True)),
                ('pf_account', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=11, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('emp_id', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
                'unique_together': {('id', 'emp_id')},
            },
        ),
    ]
